### PR TITLE
fix: files.cat: detect and handle errors when unknown path and cat dir

### LINKED ISSUE #1142: jsipfs cat on a directory not working correctly
- **Version**: 0.27.3
- **Platform**: macOS 10.13.1
- **Subsystem**: files

#### Type:
Bug

#### Severity:
High

#### Description:
`ipfs cat` on a directory displays the contents of a file in a sub directory, not the error "this dag node is a directory"

#### Steps to reproduce the error:

```sh
$ jsipfs init
initializing ipfs node at /Users/alan/.jsipfs
generating 2048-bit RSA keypair...done
peer identity: QmU8eJXWVYudzSrV5fxQuptmK1haqMG6E1eKP47xuF4e1K
to get started, enter:

	 jsipfs files cat /ipfs/QmfGBRT6BbWJd7yUc2uYdaUZJBbnEFvTqehPFoSMQ6wgdr/readme
```
lets cat that directory:
```sh
$ jsipfs cat QmfGBRT6BbWJd7yUc2uYdaUZJBbnEFvTqehPFoSMQ6wgdr
WIP

# 0.0 - Introduction

Welcome to IPFS! This tour will guide you through a few of the
features of this tool, and the most common commands. Then, it will
immerse you into the world of merkledags and the amazing things
you can do with them.

...
```
Wait, I was expecting some sort of directory error...
```sh
$ ipfs cat QmfGBRT6BbWJd7yUc2uYdaUZJBbnEFvTqehPFoSMQ6wgdr
Error: this dag node is a directory
```
...yeah like that
```sh
$ ipfs cat QmfGBRT6BbWJd7yUc2uYdaUZJBbnEFvTqehPFoSMQ6wgdr/tour/0.0-intro
WIP

# 0.0 - Introduction

Welcome to IPFS! This tour will guide you through a few of the
features of this tool, and the most common commands. Then, it will
immerse you into the world of merkledags and the amazing things
you can do with them.

...
```
weirdness, it is displaying a file in a sub folder...

### PR DESCRIPTION
**Pull request by pgte**
Should fix #1142

### CODE REVIEW

**Comment by pgte** [comment]
Tests here: https://github.com/ipfs/interface-ipfs-core/pull/182

**Comment by diasdavid** [comment]
Will wait on https://github.com/ipfs/interface-ipfs-core/pull/183#pullrequestreview-82879876 to release this fix.

File: src/core/components/files.js [hunk 1]
```diff
@@ -137,10 +137,19 @@ module.exports = function files (self) {
       pull.collect((err, files) => {
         if (err) { d.end(err) }
```
Comment (alanshaw) [inline src/core/components/files.js]: Is this missing a return?

File: src/core/components/files.js [hunk 2]
```diff
@@ -137,10 +137,19 @@ module.exports = function files (self) {
...
         if (!files || !files.length) {
-          return d.end(new Error('No such file'))
+          return d.abort(new Error('No such file'))
         }
 
-        const content = files[files.length - 1].content
+        if (files.length > 1) {
+          files = files.filter((file) => file.path === ipfsPath)
```
Comment (alanshaw) [inline src/core/components/files.js]: Here `file.path` is the path from the root e.g. `tour` and `tour/0.0-intro`, and ipfsPath is the full path e.g. `/ipfs/QmfGBRT6BbWJd7yUc2uYdaUZJBbnEFvTqehPFoSMQ6wgdr/tour`.

This filter is removing all the files from the array and so `files[0]` below is `undefined`

screen shot 2017-12-14 at 12 13 48

Comment (pgte) [reply src/core/components/files.js]: Thanks @alanshaw !
#1148 should fix this.

Comment (pgte) [reply src/core/components/files.js]: Theres's still an issue here, where "tour" dir is being filtered out prematurely because the output path doesn't match the input. Digging in...

Comment (pgte) [reply src/core/components/files.js]: ... which should be fixed f6c15c6a9d9a0847e584910879f2d0402524cc33
