### PR TITLE
fix: Return swarm http errors as json

### LINKED ISSUE #1176: Potential uncaught exception on command line
- **Version**:
js-ipfs version: 0.27.6

- **Platform**:
Linux ip-172-31-11-196 4.4.0-1048-aws #57-Ubuntu SMP Tue Jan 9 21:45:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- **Subsystem**:
jsipfs swarm connect

#### Type:
Bug

#### Severity:
High

#### Description:
When trying to connect to a peer I get an error that appears to be the result of an uncaught exception

#### Steps to reproduce the error:
1. From the command line run: `jsipfs swarm connect /libp2p-webrtc-star/dns4/star-signal.cloud.ipfs.team/wss/ipfs/QmVP7nWPqUd8fFvbrdbiViixtybEUnpc45s6vQtPM6Ce7L`
2. Note the error produced:
```
/home/ubuntu/.npm-global/lib/node_modules/ipfs/src/cli/commands/swarm/connect.js:20
        throw err
        ^

SyntaxError: Unexpected token A in JSON at position 0
    at JSON.parse (<anonymous>)
    at streamToValue (/home/ubuntu/.npm-global/lib/node_modules/ipfs/node_modules/ipfs-api/src/utils/stream-to-json-value.js:25:18)
    at concat (/home/ubuntu/.npm-global/lib/node_modules/ipfs/node_modules/ipfs-api/src/utils/stream-to-value.js:12:22)
    at ConcatStream.<anonymous> (/home/ubuntu/.npm-global/lib/node_modules/ipfs/node_modules/concat-stream/index.js:36:43)
    at emitNone (events.js:111:20)
    at ConcatStream.emit (events.js:208:7)
    at finishMaybe (/home/ubuntu/.npm-global/lib/node_modules/ipfs/node_modules/readable-stream/lib/_stream_writable.js:607:14)
    at afterWrite (/home/ubuntu/.npm-global/lib/node_modules/ipfs/node_modules/readable-stream/lib/_stream_writable.js:470:3)
    at _combinedTickCallback (internal/process/next_tick.js:144:20)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### PR DESCRIPTION
**Pull request by paulogr**
Closes #1176 

Returning errors as json the cli now receives treated messages as bellow:

```
/Users/paulogr/dev/js-ipfs/src/cli/commands/swarm/connect.js:20
        throw err
        ^

Error: no protocol with name: libp2p-webrtc-star
    at parseError (/Users/paulogr/dev/js-ipfs/node_modules/ipfs-api/src/utils/send-request.js:16:17)
    at ClientRequest.<anonymous> (/Users/paulogr/dev/js-ipfs/node_modules/ipfs-api/src/utils/send-request.js:39:14)
    at Object.onceWrapper (events.js:255:19)
    at ClientRequest.emit (events.js:160:13)
```

### CODE REVIEW

File: src/http/api/resources/swarm.js [hunk 1]
```diff
@@ -10,13 +10,22 @@ exports = module.exports
 // common pre request handler that parses the args and returns `addr` which is assigned to `request.pre.args`
 exports.parseAddrs = (request, reply) => {
   if (!request.query.arg) {
-    return reply("Argument 'addr' is required").code(400).takeover()
+    const err = 'Argument \'addr\' is required'
```
Comment (dryajov) [inline src/http/api/resources/swarm.js]: can we use '``' instead? `Argument 'addr' is required` - should work without needing to escape anything.

Comment (paulogr) [reply src/http/api/resources/swarm.js]: Sure!

Comment (paulogr) [reply src/http/api/resources/swarm.js]: Done @dryajov

**Comment by diasdavid** [comment]
Thanks @paulogr :)
