### PR TITLE
Fix js-ipfs daemon config params

### LINKED ISSUE #868: Running `daemon` in CLI screws up config
If I initialize a new repo, look at the config, run `jsipfs daemon` and then look at the config, they look different. There is some mumbo-jumbo being added in the bottom of the config. Steps to reproduce:

```
jsipfs init
# look at the config
jsipfs daemon
# ctrl+c to exit
# look at the config again
```

**Log**

```
$ IPFS_PATH=$(mktemp -d) ./node_modules/.bin/jsipfs init
initializing ipfs node at /tmp/tmp.mfw7OkcfUC
generating 2048-bit RSA keypair...done
peer identity: QmepNLSw4Ly5RNTP1sCwVLSbb6fsf2owJWtDPCUpYigg9b
WARNING: Your platform does not have native WebRTC support, it won' use any WebRTC transport
to get started, enter:

	 jsipfs files cat /ipfs/QmPZ9gcCEpqKTo6aq61g2nXGUhM4iCL3ewB6LDXZCtioEB

$ cat /tmp/tmp.mfw7OkcfUC/config
{
  "Addresses": {
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4002",
      "/ip4/127.0.0.1/tcp/4003/ws"
    ],
    "API": "/ip4/127.0.0.1/tcp/5002",
    "Gateway": "/ip4/127.0.0.1/tcp/9090"
  },
  "Discovery": {
    "MDNS": {
      "Enabled": true,
      "Interval": 10
    },
    "webRTCStar": {
      "Enabled": true
    }
  },
  "Bootstrap": [
    "/ip4/104.131.131.82/tcp/4001/ipfs/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ",
    "/ip4/104.236.176.52/tcp/4001/ipfs/QmSoLnSGccFuZQJzRadHn95W2CrSFmZuTdDWP8HXaHca9z",
    "/ip4/104.236.179.241/tcp/4001/ipfs/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM",
    "/ip4/162.243.248.213/tcp/4001/ipfs/QmSoLueR4xBeUbY9WZ9xGUUxunbKWcrNFTDAadQJmocnWm",
    "/ip4/128.199.219.111/tcp/4001/ipfs/QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu",
    "/ip4/104.236.76.40/tcp/4001/ipfs/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64",
    "/ip4/178.62.158.247/tcp/4001/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd",
    "/ip4/178.62.61.185/tcp/4001/ipfs/QmSoLMeWqB7YGVLJN3pNLQpmmEk35v6wYtsMGLzSr5QBU3",
    "/ip4/104.236.151.122/tcp/4001/ipfs/QmSoLju6m7xTh3DuokvT3886QRYqxAzb1kShaanJgW36yx"
  ],
  "Identity": {
    "PeerID": "QmepNLSw4Ly5RNTP1sCwVLSbb6fsf2owJWtDPCUpYigg9b",
    "PrivKey": "CAASqAkwggSkAgEAAoIBAQDnW+b3NkRp2++gutnwbk892Ld+5u45wwTGnjRELGWvcClZ0+0C4RH4GOwOEOrrmGhlLuoreg+0P1/GmJ6Ov6XT6TLbC+zcCmUSSWGfKDXRwVtralURAWT/KgUDcoMczDVx57BKC+Gb07paIlP5HVy8b+6MLiI8zwoonP1ol3glGFK1qHoPgvN4KoOb/QHpbMs9+X39VTzAHjH5OLGX3tmuZ3o1x/RG1xJV0Bfo3Jivi3G7tFt4FzVLWxvrsT5Z/IkCDRWG15cNddzRsylKfaMbzEUOF/jCcTWHuHaNlffbBX5i3JD98ATT2v2oxcJGl16hJOG6OWwNUSGxgbfC/VaHAgMBAAECggEBAMHDJ0ltiph52VPsiXAign0SjoNalrOLj+lkP/PElxj6P7d6lOovY2Q8Qx54rrbHes8bHoVxAcv8s5LY6Ro2iYRTrwLjFukmT4WkLX0lKQXWAWGRuVK3r0VAhNhhREuO/0e5OdyZ3MYr6ctpKpjdLXin6co/LO9umlxvNpAtIzM0dtFCCE5XswlahLFJ5YLZLu+cV+JetQGJLYkvnbCi7GTV3kG/0IbS/FUfS0rVsOe0J4muR7ZWRjq3CtYA7sC31XuW0RCYVC0qXFG5YAUrnRYFkrCGLAn/UqgxXvfSEyPCmVqYbN9PNhgaAaY27zKpKhAbCN8psIR+mMboTVVoakECgYEA/DAw+r/9zxFh8TW+Eukr6S6oHO9kBVDeGoiaoWSuEEXu2Akl28Gacgebdk2le8xi8/bAgYi6sRx05kuq+RZz1nRaSnMqIHvcaUi5LQIBWylLy6TLX21NBaQtlMbumWcpNTH6coD89PDmYhBk1pxLr6OEYxyBIcFT0KK3Ca/mJCcCgYEA6tsdaDPpwBXOlW6WU4hlZ3gGuQfUWTc5V5yo+4qWvDDqYvCcNVd/fFlmt6hfdD/QwgZkH9aMXOzfYh7jzcU9mqSpxkL173mBtprWPaTJHd+2MA2v4uPHLTfy+HTtwWhRaAK2z3vQ0O7v6rY4vLfOUVfV22OsFL4RoxCWSDO41qECgYBvOi4QGieucWM6SNLJcm/8i6h4ApmhwpYDK+bPciFXahC61eYNs6kTzAkkN4DaRj4KjfU/7Hcy8HMas5r3+5AhsPW1ym91HkwLX5jUogLJG0Cj084jC4kiCNRVvxuzKw3AuYdVg1COE8X40HQ5N3wmPj+AmyzVH3iBF5MVQbCGlwKBgF5VbNZyI634FGaJaPBclP6eg3TG5FCBkhLS5j1DSZCFxV/Abb4vSxHThyK2CsFS8LM+hfET6IVaz89FwRLh6wC2q0rrkoWCNMv4HZ3dFrtdJHzgwolMHLDZDEsoDGfnUuuIS43DmfiSQOPyFZAX9FNQCKJ6wqACSGtLOlH+FHyBAoGBAPeyTkMWjgs9cRZlkoYcA7YXcQMRHdjXboVOUQ48vVuAk/DHl/DccAUK9NOEKHCu7M1lwIZM0aD/S80xzN85MBAt4K9iYNZP5MdjdAU8iQmtlgftdNPAPpNl8XfPeiqf/F8iS7OaVIqGuEGoRr7YT1UTQyvQdeHcwNHPmoJjzSFG"
  }
}

$ IPFS_PATH=/tmp/tmp.mfw7OkcfUC ./node_modules/.bin/jsipfs daemon
Initializing daemon...
Swarm listening on /ip4/127.0.0.1/tcp/4003/ws/ipfs/QmepNLSw4Ly5RNTP1sCwVLSbb6fsf2owJWtDPCUpYigg9b
Swarm listening on /ip4/127.0.0.1/tcp/4002/ipfs/QmepNLSw4Ly5RNTP1sCwVLSbb6fsf2owJWtDPCUpYigg9b
Swarm listening on /ip4/10.185.197.123/tcp/4002/ipfs/QmepNLSw4Ly5RNTP1sCwVLSbb6fsf2owJWtDPCUpYigg9b
API is listening on: /ip4/127.0.0.1/tcp/5002
Gateway (readonly) is listening on: /ip4/127.0.0.1/tcp/9090
Daemon is ready
^CReceived interrupt signal, shutting down..

$ cat /tmp/tmp.mfw7OkcfUC/config
{
  "Addresses": {
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4002",
      "/ip4/127.0.0.1/tcp/4003/ws"
    ],
    "API": "/ip4/127.0.0.1/tcp/5002",
    "Gateway": "/ip4/127.0.0.1/tcp/9090"
  },
  "Discovery": {
    "MDNS": {
      "Enabled": true,
      "Interval": 10
    },
    "webRTCStar": {
      "Enabled": true
    }
  },
  "Bootstrap": [
    "/ip4/104.131.131.82/tcp/4001/ipfs/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ",
    "/ip4/104.236.176.52/tcp/4001/ipfs/QmSoLnSGccFuZQJzRadHn95W2CrSFmZuTdDWP8HXaHca9z",
    "/ip4/104.236.179.241/tcp/4001/ipfs/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM",
    "/ip4/162.243.248.213/tcp/4001/ipfs/QmSoLueR4xBeUbY9WZ9xGUUxunbKWcrNFTDAadQJmocnWm",
    "/ip4/128.199.219.111/tcp/4001/ipfs/QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu",
    "/ip4/104.236.76.40/tcp/4001/ipfs/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64",
    "/ip4/178.62.158.247/tcp/4001/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd",
    "/ip4/178.62.61.185/tcp/4001/ipfs/QmSoLMeWqB7YGVLJN3pNLQpmmEk35v6wYtsMGLzSr5QBU3",
    "/ip4/104.236.151.122/tcp/4001/ipfs/QmSoLju6m7xTh3DuokvT3886QRYqxAzb1kShaanJgW36yx"
  ],
  "Identity": {
    "PeerID": "QmepNLSw4Ly5RNTP1sCwVLSbb6fsf2owJWtDPCUpYigg9b",
    "PrivKey": "CAASqAkwggSkAgEAAoIBAQDnW+b3NkRp2++gutnwbk892Ld+5u45wwTGnjRELGWvcClZ0+0C4RH4GOwOEOrrmGhlLuoreg+0P1/GmJ6Ov6XT6TLbC+zcCmUSSWGfKDXRwVtralURAWT/KgUDcoMczDVx57BKC+Gb07paIlP5HVy8b+6MLiI8zwoonP1ol3glGFK1qHoPgvN4KoOb/QHpbMs9+X39VTzAHjH5OLGX3tmuZ3o1x/RG1xJV0Bfo3Jivi3G7tFt4FzVLWxvrsT5Z/IkCDRWG15cNddzRsylKfaMbzEUOF/jCcTWHuHaNlffbBX5i3JD98ATT2v2oxcJGl16hJOG6OWwNUSGxgbfC/VaHAgMBAAECggEBAMHDJ0ltiph52VPsiXAign0SjoNalrOLj+lkP/PElxj6P7d6lOovY2Q8Qx54rrbHes8bHoVxAcv8s5LY6Ro2iYRTrwLjFukmT4WkLX0lKQXWAWGRuVK3r0VAhNhhREuO/0e5OdyZ3MYr6ctpKpjdLXin6co/LO9umlxvNpAtIzM0dtFCCE5XswlahLFJ5YLZLu+cV+JetQGJLYkvnbCi7GTV3kG/0IbS/FUfS0rVsOe0J4muR7ZWRjq3CtYA7sC31XuW0RCYVC0qXFG5YAUrnRYFkrCGLAn/UqgxXvfSEyPCmVqYbN9PNhgaAaY27zKpKhAbCN8psIR+mMboTVVoakECgYEA/DAw+r/9zxFh8TW+Eukr6S6oHO9kBVDeGoiaoWSuEEXu2Akl28Gacgebdk2le8xi8/bAgYi6sRx05kuq+RZz1nRaSnMqIHvcaUi5LQIBWylLy6TLX21NBaQtlMbumWcpNTH6coD89PDmYhBk1pxLr6OEYxyBIcFT0KK3Ca/mJCcCgYEA6tsdaDPpwBXOlW6WU4hlZ3gGuQfUWTc5V5yo+4qWvDDqYvCcNVd/fFlmt6hfdD/QwgZkH9aMXOzfYh7jzcU9mqSpxkL173mBtprWPaTJHd+2MA2v4uPHLTfy+HTtwWhRaAK2z3vQ0O7v6rY4vLfOUVfV22OsFL4RoxCWSDO41qECgYBvOi4QGieucWM6SNLJcm/8i6h4ApmhwpYDK+bPciFXahC61eYNs6kTzAkkN4DaRj4KjfU/7Hcy8HMas5r3+5AhsPW1ym91HkwLX5jUogLJG0Cj084jC4kiCNRVvxuzKw3AuYdVg1COE8X40HQ5N3wmPj+AmyzVH3iBF5MVQbCGlwKBgF5VbNZyI634FGaJaPBclP6eg3TG5FCBkhLS5j1DSZCFxV/Abb4vSxHThyK2CsFS8LM+hfET6IVaz89FwRLh6wC2q0rrkoWCNMv4HZ3dFrtdJHzgwolMHLDZDEsoDGfnUuuIS43DmfiSQOPyFZAX9FNQCKJ6wqACSGtLOlH+FHyBAoGBAPeyTkMWjgs9cRZlkoYcA7YXcQMRHdjXboVOUQ48vVuAk/DHl/DccAUK9NOEKHCu7M1lwIZM0aD/S80xzN85MBAt4K9iYNZP5MdjdAU8iQmtlgftdNPAPpNl8XfPeiqf/F8iS7OaVIqGuEGoRr7YT1UTQyvQdeHcwNHPmoJjzSFG"
  },
  "_": [
    "daemon"
  ],
  "help": false,
  "enable-sharding-experiment": false,
  "enableShardingExperiment": false,
  "enable-pubsub-experiment": false,
  "enablePubsubExperiment": false,
  "$0": "node_modules/.bin/jsipfs"
}
```

### PR DESCRIPTION
**Pull request by sktt**
- Respect `--enable-experimental-pubsub`
  - Don't overload repo config with cli args (fixes #868)
  - Typo

---

I was unable to run tests, linting or anything. Did not work on node 8.1.2 or 6.11.1

### CODE REVIEW

**Comment by VictorBjelkholm** [comment]
>I was unable to run tests, linting or anything. Did not work on node 8.1.2 or 6.11.1

That seems weird, what npm version? Think npm@5 and above is not working well with aegir, but npm@4 should work ok.

Also, CI is failing, unsure of why... @diasdavid ideas?

**Comment by sktt** [comment]
```
$ DEBUG=* npm run lint                                           130 ↵

> ipfs@0.25.0 lint /home/jnes/code/ipfs/js-ipfs
> aegir-lint

[19:18:24] Starting 'lint'...
  eslint:ignored-paths Looking for ignore file in /home/jnes/code/ipfs/js-ipfs +0ms
  eslint:ignored-paths Could not find ignore file in cwd +2ms
  eslint:config Using command line config /home/jnes/code/ipfs/js-ipfs/node_modules/aegir/tasks/../config/eslintrc.yml +1ms
  eslint:config-file Loading YAML config file: /home/jnes/code/ipfs/js-ipfs/node_modules/aegir/config/eslintrc.yml +1ms
  eslint:config-file Loading standard +66ms
  eslint:config-file Attempting to resolve eslint-config-standard +0ms
  eslint:config-file Loading JS config file: /home/jnes/code/ipfs/js-ipfs/node_modules/eslint-config-standard/index.js +0ms
  eslint:plugins Failed to load plugin eslint-plugin-node. +37ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1

```

running `npm install --save-dev eslint-plugin-{standard,node}` appears to solve the problem. But i don't have enough insight in how aegir is supposed to work to know if this is the way to go

File: src/cli/commands/daemon.js [hunk 1]
```diff
@@ -16,7 +16,7 @@ module.exports = {
       default: false
     },
     'enable-pubsub-experiment': {
-      type: 'booleam',
+      type: 'boolean',
```
Comment (diasdavid) [inline src/cli/commands/daemon.js]: great catch
