### PR TITLE
fix(bootstrap:add): prevent duplicate inserts

### LINKED ISSUE #892: bootstrap:add prevent duplicate inserts
Right now it's possible to add the same address multiple times in bootstrap nodes list.

### PR DESCRIPTION
**Pull request by kenshyx**
Closes #892

### CODE REVIEW

File: test/http-api/over-ipfs-api/bootstrap.js [hunk 1]
```diff
@@ -28,6 +28,27 @@ module.exports = (ctl) => {
...
+          .then((res) => {
+            expect(res).to.be.eql({ Peers: [validIp4] })
+            return ctl.bootstrap.list()
+          })
+          .then((res) => {
+            expect(res).to.exist()
+            const insertPosition = res.Peers.indexOf(validIp4)
+            expect(insertPosition).to.not.equal(-1)
+            const duplicatePosition = res.Peers.indexOf(validIp4, insertPosition + 1)
+            expect(duplicatePosition).to.equal(-1)
```
Comment (VictorBjelkholm) [inline test/http-api/over-ipfs-api/bootstrap.js]: Add a expectation about that the bootstrap list should now only have one element in it as well.

Comment (kenshyx) [inline test/http-api/over-ipfs-api/bootstrap.js]: Line 46 verifies if the newly added peer was inserted. The bootstrap list contains the default peer list from https://github.com/ipfs/js-ipfs/tree/master/src/init-files + the ones added manually.

Comment (VictorBjelkholm) [inline test/http-api/over-ipfs-api/bootstrap.js]: As far as I can tell, you're asserting that validIp4 is not missing from the list of peers, but never asserting that the amount of peers are correct in the test-case. Ideal, minimal test-case would start with a empty bootstrap list, add the same address twice and assert that the list only contain once element.

Comment (VictorBjelkholm) [inline test/http-api/over-ipfs-api/bootstrap.js]: That way, this test would also be protected against future changes to the default bootstrap list.

Comment (kenshyx) [inline test/http-api/over-ipfs-api/bootstrap.js]: Ok, how do I set the bootstrap list to be empty without calling rm for the default bootstrap list?

File: test/http-api/over-ipfs-api/bootstrap.js [hunk 2]
```diff
@@ -28,6 +28,30 @@ module.exports = (ctl) => {
...
+            expect(res).to.be.eql({ Peers: [validIp4] })
+            return ctl.bootstrap.list()
+          })
+          .then((res) => {
+            expect(res).to.exist()
+            const insertPosition = res.Peers.indexOf(validIp4)
+            expect(insertPosition).to.not.equal(-1)
+            expect(res.Peers.length).to.equal(1)
+          })
+      })
```
Comment (diasdavid) [inline test/http-api/over-ipfs-api/bootstrap.js]: Please write tests for `core` too. The ideal would be getting `interface-ipfs-core` tests for bootstrap - https://github.com/ipfs/interface-ipfs-core/tree/master/src so that we match expectations on js-ipfs-api and js-ipfs.

File: test/http-api/over-ipfs-api/bootstrap.js (hunk 1 above)
Comment (diasdavid) [inline test/http-api/over-ipfs-api/bootstrap.js]: I'm not getting your question @VictorBjelkholm, these test nodes have their bootstrap lists empty by default:

- https://github.com/ipfs/js-ipfs/blob/master/test/utils/ipfs-factory-instance/default-config.json#L39
- https://github.com/ipfs/js-ipfs/blob/master/test/utils/ipfs-factory-daemon/default-config.json#L48

Comment (VictorBjelkholm) [inline test/http-api/over-ipfs-api/bootstrap.js]: Ah, that was what I thought... @kenshyx then you can remove the `.rm` call and just add the two addresses.

**Comment by diasdavid** [comment]
I'll go ahead and merge this. Let's not forget about the standardization of API and tests though - https://github.com/ipfs/interface-ipfs-core/issues/97

File: test/http-api/over-ipfs-api/bootstrap.js (hunk 1 above)
Comment (diasdavid) [inline test/http-api/over-ipfs-api/bootstrap.js]: @kenshyx is doing `rm` because the previous tests add up to the bootstrap peers pool
