### PR TITLE
fix(core/components/dag): make options in `put` API optional

### LINKED ISSUE #1395: `ipfs.dag.put` should be happy if i don't give it options
simply running:
```js
ipfs.dag.put(thing, (e, v) => {
  console.log(e,v)
})
```

Doesnt work right now, because it wants the put options struct.

### PR DESCRIPTION
**Pull request by PascalPrecht**
The [dag.put](https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/DAG.md#dagput) interface
takes an options object which is required, but should be optional with
decent defaults.

See dedicated test here: https://github.com/ipfs/interface-ipfs-core/pull/316

This commit implements this behaviour.

**Before**:

```js
ipfs.dag.put(obj, options, (err, cid) => {...});
```

^ Prior to this commit, without passing `options`, this call resulted in an error.

**After**:

```js
ipfs.dag.put(obj, (err, cid) => {...});
```

^ This is now perfectly fine.

Fixes #1395

License: MIT
Signed-off-by: Pascal Precht <pascal.precht@gmail.com>

### CODE REVIEW

File: src/core/components/dag.js [hunk 1]
```diff
@@ -9,6 +9,17 @@ const flattenDeep = require('lodash.flattendeep')
 module.exports = function dag (self) {
   return {
     put: promisify((dagNode, options, callback) => {
+      if (typeof options === 'function') {
+        callback = options
+      }
+
+      const optionDefaults = {
+        format: 'dag-pb',
+        hashAlg: 'sha2-256'
```
Comment (PascalPrecht) [inline src/core/components/dag.js]: @alanshaw you might wanna review those.

**Comment by PascalPrecht** [comment]
This is my first take on fixing #1395 

I also wrote simple test for it in `interface-ipfs-core`, however, I wasn't able to actually run it within my local `js-ipfs` installation yet.

That's because as soon as `interface-ipfs-core` is linked as a dependency, test commands fail due to `createCommon()` not being a function.

Here's the error message I get:

```
~/projects/ipfs/js-ipfs fix/dag-put-api*                                                                  
❯ npm run test:node:core          
                                                                                                                            
> ipfs@0.29.3 test:node:core /Users/pascalprecht/projects/ipfs/js-ipfs                                                
> aegir test -t node -f test/core/**/*.js                                                                                    
                                                              
Test Node.js                                                                
/Users/pascalprecht/projects/ipfs/interface-ipfs-core/js/src/bitswap/stat.js:11
  const common = createCommon()                             
                 ^                                                 
                                                                      
TypeError: createCommon is not a function         
    at Object.module.exports [as stat] (/Users/pascalprecht/projects/ipfs/interface-ipfs-core/js/src/bitswap/stat.js:11:18)
    at Object.keys.forEach.t (/Users/pascalprecht/projects/ipfs/interface-ipfs-core/js/src/utils/suite.js:25:15)                                                                       at Array.forEach (<anonymous>)                                                                                                                                                     at Object.suite [as bitswap] (/Users/pascalprecht/projects/ipfs/interface-ipfs-core/js/src/utils/suite.js:5:24)                                                               
    at Object.<anonymous> (/Users/pascalprecht/projects/ipfs/js-ipfs/test/core/interface/bitswap.js:35:6)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)                                                                                                           at Module.load (internal/modules/cjs/loader.js:612:32)                                                                                                                             at tryModuleLoad (internal/modules/cjs/loader.js:551:12)                                                                                                                           at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /Users/pascalprecht/projects/ipfs/js-ipfs/node_modules/aegir/node_modules/mocha/lib/mocha.js:231:27                   
    at Array.forEach (<anonymous>)                               
    at Mocha.loadFiles (/Users/pascalprecht/projects/ipfs/js-ipfs/node_modules/aegir/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/Users/pascalprecht/projects/ipfs/js-ipfs/node_modules/aegir/node_modules/mocha/lib/mocha.js:536:10)
    at Object.<anonymous> (/Users/pascalprecht/projects/ipfs/js-ipfs/node_modules/aegir/node_modules/mocha/bin/_mocha:573:18)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)                                      
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:240:19)                            
    at bootstrapNodeJSCore (internal/bootstrap/node.js:564:3)
```

I took a closer look and `createCommon` should've actually been passed down from `test/core/interface/bitswap.js`:

https://github.com/ipfs/js-ipfs/blob/master/test/core/interface/bitswap.js#L35

@alanshaw maybe you have an idea what could cause this. I should add that this error does not occur when not linking `interface-ipfs-core`.

**Comment by PascalPrecht** [comment]
Also, I wasn't sure about the commit message [scope](https://github.com/ipfs/community/blob/master/js-code-guidelines.md#scope), let me know if that needs to be updated.

**Comment by travisperson** [comment]
@PascalPrecht PR #1389 updates `js-ipfs` to work with the newer version of `interface-ipfs-core`, which now requires the `common` to be a function stead of just an object.

To run new `interface-ipfs-core` (where your test is built), you will need to rebase your changes in this branch onto #1389. 

PR #1389 should be merging soon, so we'll just need to wait for that to go in before merging this PR.

**Comment by PascalPrecht** [comment]
@travisperson @alanshaw Updated the PR accordingly.

I've also created another PR on `interface-ipfs-core` to introduce a dedicated test: https://github.com/ipfs/interface-ipfs-core/pull/316

We might wanna merge that one, before this one can go in.

**Comment by PascalPrecht** [comment]
Went with `Object.assign()` instead of object spread operators now. Hope that will satisfy CI.

**Comment by PascalPrecht** [comment]
CI is still failing, but those failing tests are unrelated to my changes.

File: src/core/components/dag.js (hunk 1 above)
Comment (alanshaw) [reply src/core/components/dag.js]: These should be the same as go-ipfs (https://ipfs.io/docs/commands/#ipfs-dag-put) i.e. dag-cbor and sha2-256

Note also that `cid` can be passed here instead of `format` & `hashAlg` that you need to take into account. See https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/DAG.md#dagput

**Comment by PascalPrecht** [comment]
> Note also that cid can be passed here instead of format & hashAlg that you need to take into account.

@alanshaw good point. The spec doesn't say anything about it, but I guess it'd make sense to through an error in case someone uses the API wrong.

Or would you prefer if `dag.put` would silently chose an option with higher priority? For example, if `cid` is given, it simply ignores `format` and `hashAlg`.

**Comment by alanshaw** [comment]
> The spec doesn't say anything about it

I'm looking here:

screen shot 2018-07-02 at 11 50 52

If the user passes a `cid` along with a `format` or `hashAlg` then I think it should callback with an error. It is likely developer error and we should inform them about it.

I'd also enforce `format` and `hashAlg` pair i.e. you shouldn't be able to pass one but not the other.

Does that sound sensible?

**Comment by PascalPrecht** [comment]
> I'm looking here

Correct! I was referring to whether the API should throw an error or not :)

> Does that sound sensible?

Alright, gonna update the PR once again!

File: src/core/components/dag.js [hunk 2]
```diff
@@ -9,6 +9,21 @@ const flattenDeep = require('lodash.flattendeep')
 module.exports = function dag (self) {
   return {
     put: promisify((dagNode, options, callback) => {
+      if (typeof options === 'function') {
+        callback = options
+      } else if (options.cid && options.format && options.hashAlg) {
+        throw new Error('Can\'t put dag node. Please provide either `cid` OR `format` and `hashAlg` options.');
+      } else if ((options.format && !options.hashAlg) || (!options.format && options.hashAlg)) {
+        throw new Error('Can\'t put dag node. Please provide `format` AND `hashAlg` options.');
```
Comment (PascalPrecht) [inline src/core/components/dag.js]: For a moment I was confused whether throwing synchronously inside `promisify()` makes sense, but I don't seem to have a handle to "reject" it either.

Looking at its testsuite, it seems to be the way to go: https://github.com/manuel-di-iorio/promisify-es6/blob/master/test.js#L79

Comment (richardschneider) [reply src/core/components/dag.js]: I would replace `throw new ...` with `return callback(new ...)`

File: src/core/components/dag.js [hunk 3]
```diff
@@ -9,6 +9,21 @@ const flattenDeep = require('lodash.flattendeep')
 module.exports = function dag (self) {
   return {
     put: promisify((dagNode, options, callback) => {
+      if (typeof options === 'function') {
+        callback = options
+      } else if (options.cid && options.format && options.hashAlg) {
```
Comment (alanshaw) [inline src/core/components/dag.js]: If we change this to `if (options.cid && (options.format || options.hashAlg))` we'll catch cid+format, cid+hashAlg AND cid+format+hashAlg. At the moment if I provide one of `hashAlg` or `format` _as well as_ `cid` it'll fall through to the next check which is for a different restriction.

Comment (PascalPrecht) [reply src/core/components/dag.js]: Oh yea, right. Much better. Let me update really quick.

File: src/core/components/dag.js [hunk 4]
```diff
@@ -9,6 +9,21 @@ const flattenDeep = require('lodash.flattendeep')
...
+        throw new Error('Can\'t put dag node. Please provide either `cid` OR `format` and `hashAlg` options.')
+      } else if ((options.format && !options.hashAlg) || (!options.format && options.hashAlg)) {
+        throw new Error('Can\'t put dag node. Please provide `format` AND `hashAlg` options.')
```
Comment (alanshaw) [inline src/core/components/dag.js]: Sorry, yes I completely missed that - you must `return callback(new Error(...))` for these

**Comment by PascalPrecht** [comment]
Thanks @alanshaw I'm happy I managed to contribute to the IPFS project.

Hope there's gonna be more opportunities to help out! :)

**Comment by PascalPrecht** [comment]
FYI: saw that latest master landed #1389, rebased this one on top of it therefore again.

**Comment by alanshaw** [comment]
> I've also noticed that this needs to be implemented in js-ipfs-api as well (https://github.com/ipfs/js-ipfs-api/blob/master/src/dag/put.js#L18). Will wait once we've decided on decent defaults and send a PR over there as well.

BTW, that would be incredible ✨

**Comment by PascalPrecht** [comment]
Gotcha. WIll take care of that.

**Comment by PascalPrecht** [comment]
> BTW, that would be incredible ✨

@alanshaw please find a WIP PR here https://github.com/ipfs/js-ipfs-api/pull/801
