### PR TITLE
fix: Add ipfs path to cli help

### LINKED ISSUE #1213: Add IPFS_PATH to CLI help
It's possible to init a repository at a different location (other than the default `~/.jsipfs`) with setting the `IPFS_PATH` environment variable. This isn't clear from the CLI help. `go-ipfs` has this information:

```
ipfs uses a repository in the local file system. By default, the repo is
located at ~/.ipfs. To change the repo location, set the $IPFS_PATH
environment variable:

    export IPFS_PATH=/path/to/ipfsrepo
```

Add this to the js-ipfs CLI as well.

### PR DESCRIPTION
**Pull request by vasco-santos**
Aiming to have a consistent menu with `go-ipfs`, I added the `IPFS_PATH` as it is presented in Go implementation.

```
ipfs uses a repository in the local file system. By default, the repo is
located at ~/.ipfs. To change the repo location, set the $IPFS_PATH
environment variable:

    export IPFS_PATH=/path/to/ipfsrepo
```

In PR https://github.com/ipfs/js-ipfs/pull/1274, it was added to `jsipfs init --help`, but it was presented before the options description, instead of in the end.

In this solution, I changed the previous implementation. Using `yargs epilog`, I added the `IPFS_PATH` message to the epilogue which is displayed for the following cases:

- `jsipfs`
- `jsipfs --help`
- `jsipfs init --help`
- `jsipfs daemon --help`

Closes #1213

### CODE REVIEW

File: src/cli/utils.js [hunk 1]
```diff
@@ -111,3 +111,7 @@ exports.rightpad = (val, n) => {
   }
   return result
 }
+
+exports.ipfsPathHelp = 'ipfs uses a repository in the local file system. By default, the repo is ' +
+  'located at ~/.jsipfs.To change the repo location, set the $IPFS_PATH environment variable:\n\n' +
```
Comment (vmx) [inline src/cli/utils.js]: Missing whitespace between `~/.jsipfs.` and `To change`.

Comment (vasco-santos) [reply src/cli/utils.js]: Good catch! Fixed
