### PR TITLE
fix: print valid ipv6 multiaddrs in terminal

### LINKED ISSUE #1853: Broken terminal output with API and Gateway on ipv6
Setting `API` and `Gateway` to listen on `/ip6/` multiaddr..

```json
   "Addresses": {                                                                                                                                                                                                                                
     "Swarm": [                                                                                                                                                                                                                                  
       "/ip4/0.0.0.0/tcp/4002",                                                                                                                                                                                                                  
       "/ip4/127.0.0.1/tcp/4003/ws"                                                                                                                                                                                                              
     ],                                                                                                                                                                                                                                          
     "API": "/ip6/::1/tcp/5002",                                                                                                                                                                                                                 
     "Gateway": "/ip6/::1/tcp/9090"                                                                                                                                                                                                              
   }, 
```

works :+1: 

..but the terminal output is broken:

```console
$ jsipfs daemon                                                                                                                                                                                                                           
[...]
API listening on /ip4//tcp/
Gateway (read only) listening on /ip4//tcp/
Web UI available at http://::1:5002/webui
Daemon is ready
```

Expected output:

```
API listening on /ip6/::1/tcp/5002
Gateway (read only) listening on /ip6/::1/tcp/9090
Web UI available at http://[::1]:5002/webui
```


ps. some quick notes from brief eyeballing:
- `apiMultiaddr` is set [here](https://github.com/ipfs/js-ipfs/blob/3cfeda9075aa14893f441f2dd18d2c0439b0664c/src/http/index.js#L165) but does not seem to be used for anything
- [`uri-to-multiaddr`](https://github.com/tableflip/uri-to-multiaddr/) should be a good replacement for `uriToMultiaddr` in `src/http/index.js`
- it may be worth thinking if we want to fix it now, or after `hapi` situation is resolved (needs to be upgraded or migrated away to something else)

### PR DESCRIPTION
**Pull request by lidel**
Fixes #1853
(easy enough to do it as a drive-by, let me know if I should rebase this after #1844  is merged)
 
Before:
```
API listening on /ip4//tcp/
Gateway (read only) listening on /ip4//tcp/
Web UI available at http://::1:5002/webui
```

After:
```
API listening on /ip6/::1/tcp/5002/http
Gateway (read only) listening on /ip6/::1/tcp/9090/http
Web UI available at http://[::1]:5002/webui
```

### CODE REVIEW

**Comment by alanshaw** [comment]
@lidel would you mind rebasing this now the Hapi 18 refactor has been merged?

**Comment by alanshaw** [comment]
ping @lidel

**Comment by lidel** [comment]
@alanshaw rebased :)

```
API listening on /ip6/::1/tcp/5002/http
Gateway (read only) listening on /ip6/::1/tcp/9090/http
Web UI available at http://[::1]:5002/webui
Daemon is ready
```

File: src/http/index.js [hunk 1]
```diff
@@ -14,9 +16,17 @@ const WS = require('libp2p-websockets')
...
 
-function uriToMultiaddr (uri) {
-  const ipPort = uri.split('/')[2].split(':')
-  return `/ip4/${ipPort[0]}/tcp/${ipPort[1]}`
+function hapiInfoToMultiaddr (info) {
+  let hostname = info.host
+  let uri = info.uri
+  // ipv6 fix
+  if (hostname.includes(':') && !hostname.startsWith('[')) {
+    // hapi 16 produces invalid URI for ipv6
```
Comment (alanshaw) [inline src/http/index.js]: Is this still needed? We use hapi 18 now...

Comment (lidel) [reply src/http/index.js]: Sadly still needed: I tried with vanilla hapi 18 and `uri` inside of `apiServer.info` was still broken (missing brackets), which produced broken `ma`:

```json
{
  "created": 1549909555055,
  "started": 1549909555222,
  "host": "::1",
  "port": 5002,
  "protocol": "http",
  "id": "foo:5989:js0o4qjz",
  "uri": "http://::1:5002",
  "address": "::1",
  "ma": "/ip4//tcp/"
}
```


Due to this the line should stay :)

```suggestion
    // hapi 18 produces invalid URI for ipv6
```
