### PR TITLE
fix: make "ipfs resolve" cli command recursive by default

### LINKED ISSUE #3692: `ipfs resolve` fails when dnslink points to another dnslink
`ipfs resolve` isn't happy about dnslinks that point to other domains.

```console
$ dig +short txt _dnslink.ipfs.io
"dnslink=/ipns/website.ipfs.io"

$ iim use js
✔ selected js-ipfs version 0.55.1

$ ipfs resolve /ipns/ipfs.io
invalid character '.' in 'website.ipfs.io'
```

### PR DESCRIPTION
**Pull request by yusefnapora**
This changes the default behavior of the `jsipfs resolve` cli command to be recursive by default. Closes #3692.

```shell
# in packages/ipfs
node src/cli.js resolve /ipns/ipfs.io
/ipfs/bafybeiagozluzfopjadeigrjlsmktseozde2xc5prvighob7452imnk76a
```

BREAKING CHANGE: resolve is now recursive by default

### CODE REVIEW

**Comment by yusefnapora** [comment]
cc @lidel / @olizilla since I haven't got my permissions sorted yet and can't request a review directly 😄

**Review by lidel — CHANGES_REQUESTED** [review]
Thanks!  CI is green, but it also means that we have no tests for this :sweat_smile: 

Perhaps you could add DNSLink test to safeguard of the default behavior in [ipfs-cli/test/resolve.js](https://github.com/ipfs/js-ipfs/blob/f25a154c36a1f08d21b10b1209021c53915cbbe3/packages/ipfs-cli/test/resolve.js#L46)?

**Comment by achingbrain** [comment]
@yusefnapora the intergration-style tests that would actually do DNS lookups are in the [interface-ipfs-core tests](https://github.com/ipfs/js-ipfs/blob/master/packages/interface-ipfs-core/src/miscellaneous/resolve.js) - please add new tests for this there.

**Comment by yusefnapora** [comment]
@achingbrain thanks for the pointer! There was already a test in there for the recursive case, but since recursive is the default, there was  no test that covered the non-recursive case.

I added a test for `recursive==false`, which flushed out an issue. `resolve` was rewriting the "scheme" portion of the resolved name to `/ipfs`, even if it actually starts with e.g. `/ipns`.

So if e.g. you have a recursive IPNS record like:

`/ipns/foo` -> `/ipns/bar` -> `ipfs/bafyxzy...`

calling `resolve('/ipns/foo', { recursive: false })` was returning `/ipfs/bar` instead of `/ipns/bar`.

Yay for tests :)

**Review by lidel — APPROVED** [review]
Lgm, tests seem to fail for unrelated reasons, @achingbrain  mind confirming and doing final review in spare time?

File: packages/interface-ipfs-core/src/miscellaneous/resolve.js [hunk 1]
```diff
@@ -94,8 +94,23 @@ module.exports = (common, options) => {
...
         .to.eq(`/ipfs/${path}`)
     })
+
+    it('should resolve IPNS link non-recursively if recursive==false', async function () {
+      this.timeout(20 * 1000)
+      // webworkers are not dialable because webrtc is not available
+      const node = (await common.spawn({ type: isWebWorker ? 'go' : undefined })).api
+      await ipfs.swarm.connect(node.peerId.addresses[0])
+      const { path } = await ipfs.add(uint8ArrayFromString('should resolve an IPNS key if recursive === false'))
+      const { id: keyId } = await ipfs.key.gen('key-name', { type: 'rsa', size: 2048 })
```
Comment (achingbrain) [inline packages/interface-ipfs-core/src/miscellaneous/resolve.js:107]: This test fails in CI because the key name is not unique:

```suggestion
      const { id: keyId } = await ipfs.key.gen(`key-name-${Math.random()}`, { type: 'rsa', size: 2048 })
```

```
ipfs:   1) interface-ipfs-core tests
ipfs:        .resolve
ipfs:          should resolve IPNS link non-recursively if recursive==false:
ipfs:      Error: Key 'key-name' already exists
ipfs:       at Keychain.createKey (file:///home/travis/build/ipfs/js-ipfs/node_modules/libp2p/src/keychain/index.js:222:45)
ipfs:       at Context2.<anonymous> (file:///home/travis/build/ipfs/js-ipfs/packages/interface-ipfs-core/src/miscellaneous/resolve.js:107:29)
ipfs: 
```

**Review by achingbrain — CHANGES_REQUESTED** [review]
This is great, but the newly added test is failing in CI

**Comment by achingbrain** [comment]
Still failing:

```
ipfs:   1) interface-ipfs-core tests
ipfs:        .resolve
ipfs:          should resolve IPNS link non-recursively if recursive==false:
ipfs:      Error: record requested for QmYQ4diQzAKmE7PFGY7fbREgiuu4kCcqo88oR7TGrMgv53 was not found in the network
ipfs:       at IpnsResolver._resolveName (/home/travis/build/ipfs/js-ipfs/packages/ipfs-core/src/ipns/resolver.js:102:23)
ipfs:       at async IpnsResolver.resolver (/home/travis/build/ipfs/js-ipfs/packages/ipfs-core/src/ipns/resolver.js:74:17)
ipfs:       at async IpnsResolver.resolve (/home/travis/build/ipfs/js-ipfs/packages/ipfs-core/src/ipns/resolver.js:52:17)
ipfs:       at async IPNS.resolve (/home/travis/build/ipfs/js-ipfs/packages/ipfs-core/src/ipns/index.js:101:22)
ipfs:       at async resolve (/home/travis/build/ipfs/js-ipfs/packages/ipfs-core/src/components/name/resolve.js:84:19)
ipfs:       at async resolve (/home/travis/build/ipfs/js-ipfs/packages/ipfs-core/src/components/resolve.js:27:24)
ipfs:       at async Context.<anonymous> (/home/travis/build/ipfs/js-ipfs/packages/interface-ipfs-core/src/miscellaneous/resolve.js:112:21)
```

**Comment by lidel** [comment]
@yusefnapora will you have time to push this one over the finish line?

**Comment by yusefnapora** [comment]
Sorry for letting this one dangle folks. I'll pick it back up this week

**Comment by yusefnapora** [comment]
The last few commits were me flailing to figure out a type check failure in `ipfs-message-port-client` that I wasn't able to reproduce locally. I finally got it to show up by installing a new version of node - I was on 14.17.0, while CI was running 14.17.1. I updated to the latest v14 release (14.17.3) and started seeing the error locally also.

The problem is that on node, `setTimeout` returns a `NodeJS.Timeout` instead of `number`, so typescript complains when trying to assign to a value of type `number|null`.

[SO to the rescue](https://stackoverflow.com/a/64071901/1292992) with a trick to define the type of `timerID` as whatever the return type of `setTimeout` actually is.

**Comment by yusefnapora** [comment]
BTW, I think the original test failure was happening because I used the same key ID (`key-name`) for both of the IPNS tests. I was running each test individually locally since running the whole suite takes a while. Once I ran them all I saw an error about `key-name` already being registered, so I changed the second test to use a different name. CI's still running, so we'll see :)

**Comment by yusefnapora** [comment]
There's [one more test failure](https://app.travis-ci.com/github/ipfs/js-ipfs/jobs/524256008), but this one is a module resolution failure in example code:

```
example-browser-browserify: > browserify src/index.js > public/bundle.js
example-browser-browserify: Error: Can't walk dependency graph: Cannot find module 'multiformats/hashes/sha2' from '/home/travis/build/ipfs/js-ipfs/node_modules/libp2p-crypto/src/keys/rsa-class.js'
example-browser-browserify:     required by /home/travis/build/ipfs/js-ipfs/node_modules/libp2p-crypto/src/keys/rsa-class.js
example-browser-browserify:     at /home/travis/build/ipfs/js-ipfs/node_modules/resolve/lib/async.js:137:35
example-browser-browserify:     at processDirs (/home/travis/build/ipfs/js-ipfs/node_modules/resolve/lib/async.js:290:39)
example-browser-browserify:     at isdir (/home/travis/build/ipfs/js-ipfs/node_modules/resolve/lib/async.js:297:32)
example-browser-browserify:     at /home/travis/build/ipfs/js-ipfs/node_modules/resolve/lib/async.js:25:69
example-browser-browserify:     at FSReqCallback.oncomplete (fs.js:192:21)
```

That sounds like something that fits into the "maintenance week" remit, so I'll check it out tomorrow :) That should probably go into its own PR though.

**Comment by yusefnapora** [comment]
@achingbrain it looks like the last failing test should be fixed by the work you did on https://github.com/ipfs/js-ipfs/issues/3742 😄

**Comment by achingbrain** [comment]
@yusefnapora awesome! I've restarted that bit of the build, it should pull down the updated modules and be good then.

**Review by achingbrain — APPROVED** [review]

**Comment by achingbrain** [comment]
I'm going to land this after #3556
