### PR TITLE
fix: cache preloaded CIDs

### LINKED ISSUE #3307: ipfs.cat calls https://node{0..3}.preload.ipfs.io/api/v0/refs?r=true&arg=<hash> on every cat
- **Version**:
```
{version: "0.50.1", repo: 9, commit: "", interface-ipfs-core: "^0.140.0", ipfs-http-client: "^47.0.0"}
```
- **Platform**:
Verified in Firefox 81 and Chrome 85 on Windows, Linux, and Macos

- **Subsystem**:
Unknown

#### Severity:
Medium

#### Description:
If there are many repeat calls of `ipfs.cat` on subpaths of a IPFS hash, then each cat will call refs on the root of the hash. The calls are identical, and they don't seem to end up the browser's indexdb, or at least they aren't referenced there again.

On large trees, you could end up downloading many gigabytes of the same refs exact refs data.

#### Steps to reproduce the error:
I discovered this while sending over improvements to moshisushi/hlsjs-ipfs-loader

If you look at the network requests made on https://charade.fu.io you will see hundreds of requests to the following 4 URLS.
```
https://node0.preload.ipfs.io/api/v0/refs?r=true&arg=QmbdmJ2JRvEFhWWzHKrAcjjBdkcs46F2N7ggZnrdKKAu4s
https://node1.preload.ipfs.io/api/v0/refs?r=true&arg=QmbdmJ2JRvEFhWWzHKrAcjjBdkcs46F2N7ggZnrdKKAu4s
https://node2.preload.ipfs.io/api/v0/refs?r=true&arg=QmbdmJ2JRvEFhWWzHKrAcjjBdkcs46F2N7ggZnrdKKAu4s
https://node3.preload.ipfs.io/api/v0/refs?r=true&arg=QmbdmJ2JRvEFhWWzHKrAcjjBdkcs46F2N7ggZnrdKKAu4s
```

There are 1360 parts times 5 different bit rates, and each part cat also triggers ipfs-js to call that refs api for the entire tree, not just for that part. The refs here are 2.5MB. As a result the browser is downloading more than 3.5GB of the same 2.5MB from the preload servers.

The movie [Charade (1963) is in the Public Domain](https://en.wikipedia.org/wiki/Charade_(1963_film)), I'm using it as a much longer Big Buck Bunny to enhance the issue. There is no copyright infringement there.

### PR DESCRIPTION
**Pull request by achingbrain**
We 'preload' most CIDs we interact with on the network. In some cases
this can mean preloading the same CID over and over again which is not
necessary.

This PR adds a LRU cache to the preloader with a default size of 1000.
The cache is used to avoid re-preloading the same CID over and over again
until it drops out of the cache.  We use a cache that will evict CIDs
over time to have some sort of upper bound on memory usage.

Fixes #3307

### CODE REVIEW

File: packages/ipfs-core/src/preload.js [hunk 1]
```diff
@@ -14,12 +17,14 @@ const log = Object.assign(
 
 /**
  * @param {Object} [options]
- * @param {boolean} [options.enabled]
- * @param {string[]} [options.addresses]
+ * @param {boolean} [options.enabled] - Whether to preload anything
+ * @param {string[]} [options.addresses] - Which preload servers to use
+ * @param {number} [options.cache] - How many CIDs to cache
```
Comment (vasco-santos) [inline packages/ipfs-core/src/preload.js:22]:
```suggestion
 * @param {number} [options.cache = 1000] - How many CIDs to cache
```

File: packages/ipfs-core/src/preload.js [hunk 2]
```diff
@@ -14,12 +17,14 @@ const log = Object.assign(
 
 /**
  * @param {Object} [options]
- * @param {boolean} [options.enabled]
- * @param {string[]} [options.addresses]
+ * @param {boolean} [options.enabled] - Whether to preload anything
+ * @param {string[]} [options.addresses] - Which preload servers to use
```
Comment (vasco-santos) [inline packages/ipfs-core/src/preload.js:21]:
```suggestion
 * @param {string[]} [options.addresses = []] - Which preload servers to use
```

File: packages/ipfs-core/src/preload.js [hunk 3]
```diff
@@ -14,12 +17,14 @@ const log = Object.assign(
 
 /**
  * @param {Object} [options]
- * @param {boolean} [options.enabled]
- * @param {string[]} [options.addresses]
+ * @param {boolean} [options.enabled] - Whether to preload anything
```
Comment (vasco-santos) [inline packages/ipfs-core/src/preload.js:20]:
```suggestion
 * @param {boolean} [options.enabled = false] - Whether to preload anything
```

**Review by vasco-santos — APPROVED** [review]
LGTM!
Left some suggestions for jsdoc default values
