### PR TITLE
fix(pubsub.peers): remove the requirement for a topic

### LINKED ISSUE #1100: pubsub/peers topic is optional
According to the [docs](https://ipfs.io/docs/api) the `topic` argument is optional in `pubsub/peers`.

[js-ipfs](https://github.com/ipfs/js-ipfs/blob/master/src/http/api/resources/pubsub.js#L102) makes it mandatory.

### PR DESCRIPTION
**Pull request by haoliangyu**
fix #1100

### CODE REVIEW

**Comment by richardschneider** [comment]
@diasdavid LGTM.  The failed travis CI has nothing to do with this PR
```
/home/travis/build/ipfs/js-ipfs/src/http/api/routes/webui.js
   1:1   error  Use the global form of 'use strict'  strict
  21:99  error  Extra semicolon                      semi
````

**Comment by haoliangyu** [comment]
@diasdavid The change has been made.

File: src/core/components/pubsub.js [hunk 1]
```diff
@@ -77,8 +77,13 @@ module.exports = function pubsub (self) {
...
       }
 
+      if (typeof topic === 'function') {
+        callback = topic
+        topic = null
+      }
+
       const peers = Array.from(self._pubsub.peers.values())
-        .filter((peer) => peer.topics.has(topic))
+        .filter((peer) => topic ? peer.topics.has(topic) : true)
```
Comment (RangerMauve) [inline src/core/components/pubsub.js]: Why bother doing the filter if you're getting all peers anyway?
